### ISSUE TITLE
Clkout

### ISSUE THREAD

**Issue by thomasverbeke** [suspaceflight/lora-tracker#4]
Hi,

Have you been able to change the clkout frequency for the LoRa semtech module to anything other then 1MHz?

I would like to have Fosc = 32 MHz
This is not really an issue with your code but I saw you set the clockout to 1MHz in your code :)

**Comment by mattbrejza** [comment]
You should just be able to change the setting of register 0x24, but I cant say I've tried setting it to 32MHz

**Comment by thomasverbeke** [comment]
Have you tried setting it to anything different than 1MHz? Also in Lora mode that register is the Fhss hop period, no?

i have not been able to change the clockout to anyting different then 1MHz so I'm wondering if its a bug of some kind or if in lora mode changing the clockout is not possible (that would be very strange though)

If it works for you than I know my efforts are not for naught :)

**Comment by thomasverbeke** [comment]
got it working, you have to switch to FSK mode (I could only switch by hard resetting (writing 0x0 register 0x01)) then set the 0x24 register and switch back to LoRa mode
